import { Users } from "@/app/page";

export async function searchUsers():Promise<Users[]> {
  return new Promise(resolve => {
    setTimeout(() => resolve(pessoas), 3000)
  })
}
export const pessoas: Users[] = [
  { id: 1, firstname: "Thiago", lastname: "Cunha", email: "thiago.cunha1@example.com", birthDate: "13-03-1996" },
  { id: 2, firstname: "Isabela", lastname: "Nunes", email: "isabela.nunes2@example.com", birthDate: "06-07-2001" },
  { id: 3, firstname: "Amanda", lastname: "Souza", email: "amanda.souza3@example.com", birthDate: "27-02-1983" },
  { id: 4, firstname: "Gustavo", lastname: "Machado", email: "gustavo.machado4@example.com", birthDate: "05-02-1960" },
  { id: 5, firstname: "Fernanda", lastname: "Lima", email: "fernanda.lima5@example.com", birthDate: "27-04-1979" },
  { id: 6, firstname: "Felipe", lastname: "Oliveira", email: "felipe.oliveira6@example.com", birthDate: "03-09-1970" },
  { id: 7, firstname: "Ana", lastname: "Ribeiro", email: "ana.ribeiro7@example.com", birthDate: "08-01-1975" },
  { id: 8, firstname: "Daniel", lastname: "Mendes", email: "daniel.mendes8@example.com", birthDate: "07-06-1964" },
  { id: 9, firstname: "Carla", lastname: "Silva", email: "carla.silva9@example.com", birthDate: "25-10-1978" },
  { id: 10, firstname: "Arthur", lastname: "Santos", email: "arthur.santos10@example.com", birthDate: "17-10-1991" },
  { id: 11, firstname: "Enzo", lastname: "Vieira", email: "enzo.vieira11@example.com", birthDate: "08-01-1970" },
  { id: 12, firstname: "Débora", lastname: "Ferreira", email: "debora.ferreira12@example.com", birthDate: "20-04-1981" },
  { id: 13, firstname: "Leonardo", lastname: "Moraes", email: "leonardo.moraes13@example.com", birthDate: "07-07-1993" },
  { id: 14, firstname: "Otávio", lastname: "Castro", email: "otavio.castro14@example.com", birthDate: "13-09-1989" },
  { id: 15, firstname: "Vitória", lastname: "Araújo", email: "vitoria.araujo15@example.com", birthDate: "14-06-1981" },
  { id: 16, firstname: "Rafael", lastname: "Rocha", email: "rafael.rocha16@example.com", birthDate: "24-03-1994" },
  { id: 17, firstname: "Helena", lastname: "Pacheco", email: "helena.pacheco17@example.com", birthDate: "23-04-1971" },
  { id: 18, firstname: "Igor", lastname: "Teixeira", email: "igor.teixeira18@example.com", birthDate: "07-02-1983" },
  { id: 19, firstname: "Marcelo", lastname: "Carvalho", email: "marcelo.carvalho19@example.com", birthDate: "03-12-1969" },
  { id: 20, firstname: "Patrícia", lastname: "Fernandes", email: "patricia.fernandes20@example.com", birthDate: "19-12-1999" },
  { id: 21, firstname: "Clara", lastname: "Martins", email: "clara.martins21@example.com", birthDate: "13-05-1997" },
  { id: 22, firstname: "João", lastname: "Pires", email: "joao.pires22@example.com", birthDate: "26-08-1966" },
  { id: 23, firstname: "Sophia", lastname: "Mendes", email: "sophia.mendes23@example.com", birthDate: "13-09-1966" },
  { id: 24, firstname: "Júlia", lastname: "Nascimento", email: "julia.nascimento24@example.com", birthDate: "18-05-1993" },
  { id: 25, firstname: "Beatriz", lastname: "Almeida", email: "beatriz.almeida25@example.com", birthDate: "12-11-1983" },
  { id: 26, firstname: "William", lastname: "Ribeiro", email: "william.ribeiro26@example.com", birthDate: "19-01-1989" },
  { id: 27, firstname: "Carla", lastname: "Costa", email: "carla.costa27@example.com", birthDate: "02-10-1984" },
  { id: 28, firstname: "Daniel", lastname: "Gonçalves", email: "daniel.goncalves28@example.com", birthDate: "18-05-1983" },
  { id: 29, firstname: "Eduarda", lastname: "Barbosa", email: "eduarda.barbosa29@example.com", birthDate: "23-08-1994" },
  { id: 30, firstname: "Pedro", lastname: "Freitas", email: "pedro.freitas30@example.com", birthDate: "04-05-1971" },
  { id: 31, firstname: "Amanda", lastname: "Martins", email: "amanda.martins31@example.com", birthDate: "10-09-1967" },
  { id: 32, firstname: "Carlos", lastname: "Reis", email: "carlos.reis32@example.com", birthDate: "25-02-1995" },
  { id: 33, firstname: "Débora", lastname: "Melo", email: "debora.melo33@example.com", birthDate: "16-04-1991" },
  { id: 34, firstname: "Enzo", lastname: "Figueiredo", email: "enzo.figueiredo34@example.com", birthDate: "18-03-1999" },
  { id: 35, firstname: "Fernanda", lastname: "Pinto", email: "fernanda.pinto35@example.com", birthDate: "04-09-1974" },
  { id: 36, firstname: "Gustavo", lastname: "Sales", email: "gustavo.sales36@example.com", birthDate: "19-03-1998" },
  { id: 37, firstname: "Helena", lastname: "Cordeiro", email: "helena.cordeiro37@example.com", birthDate: "24-04-1969" },
  { id: 38, firstname: "Igor", lastname: "Nunes", email: "igor.nunes38@example.com", birthDate: "25-06-1973" },
  { id: 39, firstname: "Júlia", lastname: "Azevedo", email: "julia.azevedo39@example.com", birthDate: "25-10-1972" },
  { id: 40, firstname: "Lucas", lastname: "Duarte", email: "lucas.duarte40@example.com", birthDate: "06-05-1962" },
  { id: 41, firstname: "Pedro", lastname: "Coelho", email: "pedro.coelho41@example.com", birthDate: "15-02-1982" },
  { id: 42, firstname: "Beatriz", lastname: "Ramos", email: "beatriz.ramos42@example.com", birthDate: "13-02-1992" },
  { id: 43, firstname: "Luana", lastname: "Miranda", email: "luana.miranda43@example.com", birthDate: "10-05-1972" },
  { id: 44, firstname: "Caio", lastname: "Neves", email: "caio.neves44@example.com", birthDate: "03-02-1998" },
  { id: 45, firstname: "Mariana", lastname: "Moraes", email: "mariana.moraes45@example.com", birthDate: "04-03-1986" },
  { id: 46, firstname: "Ricardo", lastname: "Gomes", email: "ricardo.gomes46@example.com", birthDate: "18-02-1963" },
  { id: 47, firstname: "Camila", lastname: "Cardoso", email: "camila.cardoso47@example.com", birthDate: "07-03-1967" },
  { id: 48, firstname: "Vinicius", lastname: "Pinto", email: "vinicius.pinto48@example.com", birthDate: "07-10-1979" },
  { id: 49, firstname: "Manuela", lastname: "Almeida", email: "manuela.almeida49@example.com", birthDate: "21-02-1973" },
  { id: 50, firstname: "Arthur", lastname: "Nascimento", email: "arthur.nascimento50@example.com", birthDate: "03-04-1977" }
];